version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
      MYSQL_LOCAL_INFILE: 1
    volumes:
      - mysql-data:/var/lib/mysql
      - /Users/ysingh/Downloads/mysql_files_csv:/var/lib/mysql-files
    ports:
      - "3306:3306"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  mysql-data:
    driver: local
